version: '3'
services:
  "web-application":
    build: "./web-application/"
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - JWT_KEY=jsonWebTokenKey
    volumes:
      - "./web-application/src:/web-application/src"
    depends_on:
      - database
  database:
    build: ./database
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=theRootPassword
      - MYSQL_DATABASE=webAppDatabase
  redis:
    build: ./redis
    ports:
      - "6379:6379"
